import Head from "next/head";
// import styles from '@/styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.css";
import Navigation from "@/components/Navigation";
import Main from "@/components/Main";
import Data from "@/components/Data";
import Dev from "@/components/Dev";
import Footer from "@/components/Footer";

import { initializeIcons } from '@fluentui/font-icons-mdl2';


export default function Home() {
  
  initializeIcons();
  return (
    <>
      <Head>
        <title>Lebenslauf Lars Eschweiler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
        <Navigation />
        <Main />
        
        <Data />

        <Dev />

        <Footer />
   
    </>
  );
}
